// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Example usage moved inside a main function for demonstration purposes.
Future<void> main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT1Jy8oknFPeCI1JNLps4CLJ-3DRT-kI8',
    appId: '1:199668291946:web:7b1cdf1a2684cf0c50ed13',
    messagingSenderId: '199668291946',
    projectId: 'wemoove-1a4f0',
    authDomain: 'wemoove-1a4f0.firebaseapp.com',
    storageBucket: 'wemoove-1a4f0.firebasestorage.app',
    measurementId: 'G-FKH7NFH97V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrLdGqYBMsZ4H_x4xrEYo4lAeKt3ekqg8',
    appId: '1:199668291946:android:e28f75184eaf916250ed13',
    messagingSenderId: '199668291946',
    projectId: 'wemoove-1a4f0',
    storageBucket: 'wemoove-1a4f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhGSmcjWHA-AQIaVxMy1hccnoSW7qc8Q',
    appId: '1:199668291946:ios:e7afe78bd736b39050ed13',
    messagingSenderId: '199668291946',
    projectId: 'wemoove-1a4f0',
    storageBucket: 'wemoove-1a4f0.firebasestorage.app',
    iosBundleId: 'com.example.flutterWemoove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVhGSmcjWHA-AQIaVxMy1hccnoSW7qc8Q',
    appId: '1:199668291946:ios:e7afe78bd736b39050ed13',
    messagingSenderId: '199668291946',
    projectId: 'wemoove-1a4f0',
    storageBucket: 'wemoove-1a4f0.firebasestorage.app',
    iosBundleId: 'com.example.flutterWemoove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT1Jy8oknFPeCI1JNLps4CLJ-3DRT-kI8',
    appId: '1:199668291946:web:9560f178ffb4859850ed13',
    messagingSenderId: '199668291946',
    projectId: 'wemoove-1a4f0',
    authDomain: 'wemoove-1a4f0.firebaseapp.com',
    storageBucket: 'wemoove-1a4f0.firebasestorage.app',
    measurementId: 'G-6SVYYB1XSS',
  );
}
